services:
  aws:
    image: organs/awscli
    env_file:
      - .env
    volumes:
      - "./:/app"
    working_dir: /app
  terraform:
    env_file:
      - .env   
    build:
      context: .
      dockerfile: terraform.dockerfile
    volumes:
      - "./:/app"
    working_dir: /app
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
  unit-test:
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    volumes:
      - "./:/app"
    build:
      context: .
      dockerfile: rspec.dockerfile
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
  website:
    build:
      context: .
    ports:
      - "80:80"
